Question 1


In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Array: [10 20 30 40 50]
Shape: (5,)
Size: 5
Data type: int64


Question 2


In [2]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Question 3


In [3]:
zeros = np.zeros((3, 4))
ones = np.ones((3, 4))
identity = np.eye(3)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity matrix:\n", identity)

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Question 4


In [4]:
even_numbers = np.arange(10, 51, 2)
print(even_numbers)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Question 5


In [5]:
arr = np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Question 6


In [6]:
a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]


Question 7


In [7]:
arr = np.array([1, 2, 3, 4, 5])
print("Square:", arr ** 2)
print("Cube:", arr ** 3)

Square: [ 1  4  9 16 25]
Cube: [  1   8  27  64 125]


Question 8


In [8]:
arr = np.array([100, 200, 300, 400])
increased = arr * 1.15
print(increased)

[115. 230. 345. 460.]


Question 9


In [9]:
a = np.array([10, 25, 30, 45])
b = np.array([15, 20, 35, 40])

print("Maximum:", np.maximum(a, b))
print("Minimum:", np.minimum(a, b))

Maximum: [15 25 35 45]
Minimum: [10 20 30 40]


Question 10


In [10]:
arr = np.arange(21)

print("First five:", arr[:5])
print("Last five:", arr[-5:])
print("Index 5 to 15:", arr[5:16])
print("Every second element:", arr[::2])

First five: [0 1 2 3 4]
Last five: [16 17 18 19 20]
Index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14 15]
Every second element: [ 0  2  4  6  8 10 12 14 16 18 20]


Question 11


In [11]:
arr = np.arange(10)
arr[:5] = 100
print(arr)

[100 100 100 100 100   5   6   7   8   9]


Question 12


In [12]:
original = np.array([10, 20, 30, 40, 50])

view = original[1:4]
view[0] = 999
print("After changing the view:", original)

original = np.array([10, 20, 30, 40, 50])
copy_arr = original[1:4].copy()
copy_arr[0] = 999
print("Original after changing the copy:", original)
print("Copy:", copy_arr)

After changing the view: [ 10 999  30  40  50]
Original after changing the copy: [10 20 30 40 50]
Copy: [999  30  40]


Question 13


In [13]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[::-1])

[5 4 3 2 1]


Question 14


In [14]:
matrix = np.array([[10, 20, 30],
                    [40, 50, 60],
                    [70, 80, 90]])

print("Second row:", matrix[1])
print("Third column:", matrix[:, 2])
print("Element 50:", matrix[1, 1])

Second row: [40 50 60]
Third column: [30 60 90]
Element 50: 50


Question 15


In [15]:
sub_matrix = matrix[:2, 1:]
print(sub_matrix)

[[20 30]
 [50 60]]


Question 16


In [16]:
matrix = np.arange(1, 26).reshape(5, 5)

print("First row:", matrix[0])
print("Last column:", matrix[:, -1])
print("Middle element:", matrix[2, 2])
print("Top-left 3x3 matrix:\n", matrix[:3, :3])

First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Middle element: 13
Top-left 3x3 matrix:
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


Question 17


In [17]:
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Question 18


In [18]:
arr = np.arange(1, 11)
matrix = arr.reshape(2, 5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Question 19


In [19]:
matrix = np.arange(1, 13).reshape(3, 4)
print("Original:\n", matrix)
print("Transpose:\n", matrix.T)

Original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transpose:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Question 20


In [20]:
arr3d = np.arange(24).reshape(2, 3, 4)

print("Original shape:", arr3d.shape)
print("transpose(1, 0, 2) shape:", arr3d.transpose(1, 0, 2).shape)
print("swapaxes(0, 2) shape:", arr3d.swapaxes(0, 2).shape)

Original shape: (2, 3, 4)
transpose(1, 0, 2) shape: (3, 2, 4)
swapaxes(0, 2) shape: (4, 3, 2)


Question 21


In [21]:
A = np.arange(1, 10).reshape(3, 3)
B = np.arange(9, 0, -1).reshape(3, 3)

print("A + B:\n", A + B)
print("A * B:\n", A * B)

A + B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
A * B:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


Question 22


In [22]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

print(np.dot(A, B))

[[ 58  64]
 [139 154]]


Question 23


In [23]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

AT = A.T
print("Transpose:\n", AT)
print("A.T dot A:\n", np.dot(AT, A))

Transpose:
 [[1 4]
 [2 5]
 [3 6]]
A.T dot A:
 [[17 22 27]
 [22 29 36]
 [27 36 45]]


Question 24


In [24]:
arr = np.array([1, 4, 9, 16, 25])
print(np.sqrt(arr))

[1. 2. 3. 4. 5.]


Question 25


In [25]:
arr = np.array([0, 1, 2, 3])
print(np.exp(arr))

[ 1.          2.71828183  7.3890561  20.08553692]


Question 26


In [26]:
np.random.seed(42)
arr = np.random.randn(5)

print("Random array:", arr)
print("Square root of absolute values:", np.sqrt(np.abs(arr)))
print("Exponential:", np.exp(arr))
print("Absolute values:", np.abs(arr))

Random array: [ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
Square root of absolute values: [0.70477951 0.37183908 0.80479099 1.23411096 0.48389397]
Exponential: [1.64331272 0.87086849 1.91111824 4.58609939 0.79124045]
Absolute values: [0.49671415 0.1382643  0.64768854 1.52302986 0.23415337]


Question 27


In [27]:
np.random.seed(42)
a = np.random.rand(5)
b = np.random.rand(5)

print("A:", a)
print("B:", b)
print("Element-wise maximum:", np.maximum(a, b))

A: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
B: [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
Element-wise maximum: [0.37454012 0.95071431 0.86617615 0.60111501 0.70807258]


Question 28


In [28]:
marks = np.array([35, 72, 48, 90, 55, 28])
result = np.where(marks < 40, 0, marks)
print(result)

[ 0 72 48 90 55  0]


Question 29


In [29]:
income = np.array([35000, 50000, 72000, 48000, 90000])
classification = np.where(income >= 50000, "High", "Low")
print(classification)

['Low' 'High' 'High' 'Low' 'High']


Question 30


In [30]:
arr = np.array([10, 25, 31, 45, 20, 60])
result = np.where(arr > 30, 100, arr)
print(result)

[ 10  25 100 100  20 100]


Question 31


In [31]:
matrix = np.arange(1, 10).reshape(3, 3)

print("Sum:", np.sum(matrix))
print("Mean:", np.mean(matrix))
print("Variance:", np.var(matrix))
print("Standard deviation:", np.std(matrix))

Sum: 45
Mean: 5.0
Variance: 6.666666666666667
Standard deviation: 2.581988897471611


Question 32


In [32]:
matrix = np.arange(1, 10).reshape(3, 3)

print("Row-wise sums:", np.sum(matrix, axis=1))
print("Column-wise sums:", np.sum(matrix, axis=0))

Row-wise sums: [ 6 15 24]
Column-wise sums: [12 15 18]


Question 33


In [33]:
marks = np.array([72, 85, 68, 90, 55, 77, 81, 63, 95, 70])

print("Mean:", np.mean(marks))
print("Standard deviation:", np.std(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))

Mean: 75.6
Standard deviation: 11.783038657324349
Minimum: 55
Maximum: 95


Question 34


In [34]:
values = np.array([True, True, False, True])

print("any():", np.any(values))
print("all():", np.all(values))

all_true = np.array([True, True, True])
print("all() when every value is True:", np.all(all_true))

any(): True
all(): False
all() when every value is True: True


Question 35


In [35]:
np.random.seed(42)
arr = np.random.rand(10)
print("Original:", arr)
print("Sorted:", np.sort(arr))

Original: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]
Sorted: [0.05808361 0.15599452 0.15601864 0.37454012 0.59865848 0.60111501
 0.70807258 0.73199394 0.86617615 0.95071431]


Question 36


In [36]:
arr = np.array([10, 20, 10, 30, 20, 40, 30, 50])
print(np.unique(arr))

[10 20 30 40 50]


Question 37


In [37]:
marks = np.array([75, 80, 75, 90, 80, 65, 90, 70])
print(np.unique(marks))

[65 70 75 80 90]


Question 38


In [38]:
arr = np.array([10, 20, 30, 40, 50])
selected = np.array([20, 25, 50])

print(np.in1d(selected, arr))

AttributeError: module 'numpy' has no attribute 'in1d'

Question 39


In [39]:
marks = np.array([
    [65, 70, 55],
    [40, 45, 50],
    [80, 75, 85],
    [55, 60, 58],
    [30, 45, 35],
    [90, 88, 92],
    [50, 52, 48],
    [72, 68, 75],
    [42, 39, 45],
    [60, 65, 70]
])

total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
qualified = np.where(average >= 50)[0]

print("Total marks:", total)
print("Average marks:", average)
print("Student indices with average >= 50:", qualified)
print("Student numbers:", qualified + 1)

Total marks: [190 135 240 173 110 270 150 215 126 195]
Average marks: [63.33333333 45.         80.         57.66666667 36.66666667 90.
 50.         71.66666667 42.         65.        ]
Student indices with average >= 50: [0 2 3 5 6 7 9]
Student numbers: [ 1  3  4  6  7  8 10]


Question 40


In [40]:
matrix = np.arange(1, 17).reshape(4, 4)

print("Matrix:\n", matrix)
print("Transpose:\n", matrix.T)
print("Row-wise sums:", np.sum(matrix, axis=1))
print("Column-wise sums:", np.sum(matrix, axis=0))
print("Mean:", np.mean(matrix))
print("Maximum:", np.max(matrix))
print("Minimum:", np.min(matrix))
print("Central 2x2:\n", matrix[1:3, 1:3])

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row-wise sums: [10 26 42 58]
Column-wise sums: [28 32 36 40]
Mean: 8.5
Maximum: 16
Minimum: 1
Central 2x2:
 [[ 6  7]
 [10 11]]


Question 41


In [41]:
np.random.seed(42)
data = np.random.randn(20)

print("Data:", data)
print("Mean:", np.mean(data))
print("Standard deviation:", np.std(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Sorted values:", np.sort(data))
print("Negative values replaced with zero:", np.where(data < 0, 0, data))

Data: [ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
  1.57921282  0.76743473 -0.46947439  0.54256004 -0.46341769 -0.46572975
  0.24196227 -1.91328024 -1.72491783 -0.56228753 -1.01283112  0.31424733
 -0.90802408 -1.4123037 ]
Mean: -0.17129856144182892
Standard deviation: 0.9357199588937781
Minimum: -1.913280244657798
Maximum: 1.5792128155073915
Sorted values: [-1.91328024 -1.72491783 -1.4123037  -1.01283112 -0.90802408 -0.56228753
 -0.46947439 -0.46572975 -0.46341769 -0.23415337 -0.23413696 -0.1382643
  0.24196227  0.31424733  0.49671415  0.54256004  0.64768854  0.76743473
  1.52302986  1.57921282]
Negative values replaced with zero: [0.49671415 0.         0.64768854 1.52302986 0.         0.
 1.57921282 0.76743473 0.         0.54256004 0.         0.
 0.24196227 0.         0.         0.         0.         0.31424733
 0.         0.        ]


Question 42


In [42]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

addition = A + B
elementwise_multiplication = A * B
matrix_multiplication = np.dot(A, B)
transpose_A = A.T
maximum = np.maximum(A, B)
minimum = np.minimum(A, B)

print("Element-wise addition:\n", addition)
print("Element-wise multiplication:\n", elementwise_multiplication)
print("Matrix multiplication:\n", matrix_multiplication)
print("Transpose of A:\n", transpose_A)
print("Maximum:\n", maximum)
print("Minimum:\n", minimum)

Element-wise addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Element-wise multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpose of A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Maximum:
 [[9 8 7]
 [6 5 6]
 [7 8 9]]
Minimum:
 [[1 2 3]
 [4 5 4]
 [3 2 1]]


Question 43


In [43]:
arr = np.arange(1, 25)
matrix = arr.reshape(4, 6)

print("4x6 matrix:\n", matrix)
print("Selected rows (1st and 3rd):\n", matrix[[0, 2]])
print("Selected columns (2nd and 5th):\n", matrix[:, [1, 4]])
print("Transpose:\n", matrix.T)

print("Row means:", np.mean(matrix, axis=1))
print("Column means:", np.mean(matrix, axis=0))
print("Row minimums:", np.min(matrix, axis=1))
print("Column maximums:", np.max(matrix, axis=0))
print("Unique values:", np.unique(matrix))

4x6 matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Selected rows (1st and 3rd):
 [[ 1  2  3  4  5  6]
 [13 14 15 16 17 18]]
Selected columns (2nd and 5th):
 [[ 2  5]
 [ 8 11]
 [14 17]
 [20 23]]
Transpose:
 [[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]
Row means: [ 3.5  9.5 15.5 21.5]
Column means: [10. 11. 12. 13. 14. 15.]
Row minimums: [ 1  7 13 19]
Column maximums: [19 20 21 22 23 24]
Unique values: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
